# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MyJournals' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyJournals
  pod 'SwiftLint'
  pod 'BNRCoreDataStack', '~> 2.3'
  pod 'IQKeyboardManagerSwift', '~> 5.0'
  pod 'ImagePicker', '~> 3.0'
  pod 'ESPullToRefresh', '~> 2.7'
end
